### ISSUE TITLE
Logo Design 

### ISSUE THREAD

**Issue by nunojesus** [tensorflow/moonlight#19]
Hi, concrats for your project!
Do you have a logotype? If you need one I can do it for free, I love to contribute to opensource projects, so if you want one just say it, Im here to help!

Greetings!
Nuno Jesus

**Comment by ringw** [comment]
Hi Nuno,

Thank you! We don't have any plans for a logo, and would welcome any contributions. If you are interested, feel free to check in a logo and embed it in "README.md", and open a pull request. Depending on the [CLA](https://github.com/tensorflow/moonlight/blob/master/CONTRIBUTING.md) that you sign on your Google account, either you or your employer will retain the copyright for your work. I don't have much in mind, but something inspired by sheet music notation would be nice!

**Comment by ringw** [comment]
Thanks, these are great! I think I like the red logo on the left. Feel free to open a PR with the logo. Could you maybe include a PNG and vector version in a "logo" subdirectory?

**Comment by nunojesus** [comment]
Hi Im happy that you like the proposal logo, so now I will prepair the files to send to you, I will send Png and other editable files.

Greetings!
Nuno Jesus

**Comment by ringw** [comment]
Added the logo. Thank you again for your work!
