### ISSUE TITLE
Export chords in MusicXML

### ISSUE THREAD

**Issue by ringw** [tensorflow/moonlight#24]
Noteheads should be treated as a single chord if they all have the same glyph.note.start_time and glyph.note.end_time (when we add voices, they should be in the same voice as well).

For now, we can assume that notes in a single chord are consecutive in the Staff.glyph repeated field. They also need to be consecutive in the MusicXML output, and all notes after the first note in the chord should have a <chord/> tag, which indicates that they're in the same chord as the previous note.

**Comment by jsawruk** [comment]
Suggestion:
In musicxml.py, score_to_musicxml, keep track of the previous note start_time and end_time. If the current note matches both of these, add the `<chord />` element to the note. These counters would reset on each measure.

```
# Initialize the counters
previous_note_start_time = 0
previous_note_end_time = 0
for glyph in staff.glyph:
...
note = _glyph_to_note(glyph)
if note is not None:

  # New code
  if (glyph.note.start_time == previous_note_start_time 
       and glyph.note.end_time == previous_note_end_time):
    # Append the <chord /> element to this note
    etree.SubElement(note, 'chord')
  # Update the counters
  previous_note_start_time = glyph.note.start_time
  previous_note_end_time = glyph.note.end_time
  # End new code

  measure.append(note)
```

**Comment by ringw** [comment]
Thanks, this looks great!

**Comment by ringw** [comment]
Fixed.
