### ISSUE TITLE
a problem about @com_google_protobuf

### ISSUE THREAD

**Issue by AaronLee150102** [tensorflow/moonlight#61]
When I execute: bazel build moonlight:omr,there is a ERROR: 
_/home/aaron/my_virtualenv/moonlight-o/moonlight/BUILD:34:1: no such package '@com_google_protobuf//': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement._
I am using bazel-0-20-0 and libprotoc 3.6.1,but there is still an error.how can I solve this problem.I

**Comment by DaveGeneral** [comment]
follow the hint "Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule."
