### ISSUE TITLE
ImportError: cannot import name 'music_pb2'

### ISSUE THREAD

**Issue by Cooperdamega** [tensorflow/moonlight#78]
I tried following the command line usage on the README file. Bazel was able to build successfully, but trying to print the Score message gives me this error:

from protobuf import music_pb2 as protobuf_dot_music__pb2
ImportError: cannot import name 'music_pb2' from 'protobuf' (\\?\C:\Users\UserName\AppData\Local\Temp\Bazel.runfiles_fvslv94m\runfiles\__main__\moonlight\protobuf\__init__.py)

**Comment by ionode** [comment]
I have the same (or at least related) issue, bazel build moonlight succesfully yet music_pb2 cannot be imported

Command(cmd)log:

C:\Users\Mariu\OMR\moonlight\bazel-bin\moonlight>omr moonlight/testdata/IMSLP00747-000.png
C:\Users\Mariu\OMR\venv\lib\site-packages\librosa\core\audio.py:33: UserWarning: Could not import scikits.samplerate. Falling back to scipy.signal
  warnings.warn('Could not import scikits.samplerate. '
Traceback (most recent call last):
  File "\\?\C:\Users\Mariu\AppData\Local\Temp\Bazel.runfiles_i9rwhti1\runfiles\__main__\moonlight\omr.py", line 30, in <module>
    from moonlight import conversions
  File "\\?\C:\Users\Mariu\AppData\Local\Temp\Bazel.runfiles_i9rwhti1\runfiles\__main__\moonlight\conversions\__init__.py", line 21, in <module>
    from moonlight.conversions.musicxml import score_to_musicxml
  File "\\?\C:\Users\Mariu\AppData\Local\Temp\Bazel.runfiles_i9rwhti1\runfiles\__main__\moonlight\conversions\musicxml.py", line 30, in <module>
    from moonlight.protobuf import musicscore_pb2
  File "\\?\C:\Users\Mariu\AppData\Local\Temp\Bazel.runfiles_i9rwhti1\runfiles\__main__\moonlight\protobuf\musicscore_pb2.py", line 15, in <module>
    from protobuf import music_pb2 as protobuf_dot_music__pb2
ImportError: cannot import name 'music_pb2'

i've tried googling the issue but ive found no solutions thusfar.

**Comment by ringw** [comment]
I'll clarify the README, we should have instructions for supporting Windows Subsystem Linux but not for Windows itself. The codebase is generally written to be platform-agnostic, but it looks like the Bazel directory structure may be inconsistent on Windows.

**Comment by Domigome** [comment]
Pleasee Update the README :')

After trying to run moonlight on a M1 Mac, I discovered they are not compatible.

Now I have run into this error running on Windows, so this option is discarded as well.

**Comment by ringw** [comment]
Thanks all.

This project isn't currently active, and our end goal is Cloud Compute over a static corpus of PNGs, so we are only looking at Linux. For debugging, the most comprehensive cross-platform solution would be a Linux VirtualBox and Jupyter notebook with port forwarding. It didn't reach the point yet of producing fuzzy, low-quality, but meaningful MusicXML files in bulk, so we're not working on a regular release yet which would get around limitations of building a Bazel project.
